### ISSUE TITLE
Not redirected to correct page after login

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#828] opened 2014-04-04 11:13 UTC
Hi guys,

As mentioned in our call, when I click on a link when logged out of the site, I'm not redirected to the correct page after I log in. Thanks for looking into it!

Paulina

**Comment by Paulina-Rosetta** [comment] 2016-03-15 12:31
@alanbarrett This is still a problem and I keep forgetting to mention it to you :-)

**Comment by alanbarrett** [comment] 2016-03-30 16:10
I have determined the cause for this. It worked on the test server because Trommons was not in the document root. I have removed a check that the Trommons sub-folder was part of the Path (this test fails on the live server because there is no sub-folder as Trommons is in the document root). Even though the change is very simple, I had quite a few cases to test as there was a possibility that the behaviour would be different for Admins and there are differences for Google login and Username/Password login. Also I needed to test users with and without a profile. All this is now done and everything works.

However, I have not yet committed this change to the live server (master branch) because I have a question to ask.

We recently added code to bring people to edit their profile. However there is now a slight conflict between that feature and this fix...

1) This fix will bring someone to the link they have clicked on after they login.
2) So they will not be brought to edit their profile.
3) However anyone who goes to trommons.org or trommons.org/login/ WILL be brought to edit their profile, if they have not previously set their Native Language/Country.

So what should I do... implement my current change as defined in (1), (2) and (3) above? I think this is probably the correct behaviour, but I could do the alternative of changing the code so that they will be brought to edit their profile (if the Native Language is not set) when they click on a link, rather than going to the link (although I am not so keen on this).

What do you think?

    Alan.

**Comment by alanbarrett** [comment] 2016-03-31 14:26
Now implemented in master branch (as outlined above and after discussion with Alba who pointed out that if they are getting (Task Stream) links they have probably edited their profile): commit 1f165683b263c56c126596a83b7764cf7e8b286b

    Alan.

**Closed by alanbarrett** 2016-03-31 14:26 UTC
Labels: bug, UI, useability
