### ISSUE TITLE
Creating separate html files for FAQ

### ISSUE THREAD

**Issue by Wasala** [TheRosettaFoundation/SOLAS-Match#1122] opened 2015-02-09 16:23 UTC
As it stands, it is very difficult to update the FAQ because of  the distributed nature of FAQ's content within the strings files. To facilitate easy updating of FAQ content (as well as easy localisation), the content can be stored in plain html format (excluding header and footer info) for each language within the localisation folder (ui/localisation/) (e.g. FAQ_en.html, FAQ_es.html, FAQ_it.html). Then depending on user's preferred UI language, the relevant FAQ can be displayed with the header and footer information.

This will also have following benefits:
1) isolates FAQ content from stings.xml and strings.xml can mainly be used for non-static content. 
2) screenshots/localised images can be used within the FAQ
3) in place localisation of html files - for localisers

@spaceindaver, @TheIceMageX50  What are your views on this idea?

**Comment by TheIceMageX50** [comment] 2015-02-09 16:46
It might not be a big issue but one thought that has come to mind is, if you do take this suggested approach, "How will you handle the cases where the same string is used twice, like how FAQ questions are listed and then repeated later with answers?"

I'm sure a lot of translators would be competent enough to notice a repeated sentence but when translating a lot at once the chance of mistakes and such could rise. As such, I like how the present system by design makes sure a translator does not give 2 translations of one string. Would the translators typically be familiar enough with HTML? I suppose they would if they're doing this kind of translation work, right?

**Comment by Wasala** [comment] 2015-02-09 16:57
@TheIceMageX50 Translators usually use tools (e.g. omegaT, virtaal, trados, catalyst etc) and majority of these tools support html by default. These tools keep track of previously translated contents and help translators to translate new content by suggesting partially or fully translated strings mainly by using previously translated content (this is by maintaining/using translation memories TMs).  So in other words, I am pretty sure this is not a huge problem for translators. My concern is that every time someone tries to access FAQ, it will result in a local file inquiry in the live server. I don't think it is a huge issue but it is better if we could minimise the file system access. Any ideas :) ?

**Comment by spaceindaver** [comment] 2015-02-09 20:30
Hey, I'm not sure about the benefits of this approach. One of the main advantages of the strings.xml file is that there is a seperation of content and layout. The FAQ page can be defined as a template with no content whatsoever and just import the appropriate content depending on the user's settings. This is a big advantage as the fallback stuff (i.e. rendering a default language string instead of the user's language string when the user's language is unavailable) is already implemented and would not need to be rewritten to handle this new format. It also makes it more difficult to translate the site as a whole as there are now two formats that need to be processed in order to localise the site, namely the strings file and the html pages. I would advise against this as it fragments the localisation files and makes it much more difficult to manage. If you are having trouble adding new FAQ sections then I would suggest updating the strings file to make it easier instead of replacing the strings file with a different format. I really don't see any advantage to the approach you have suggested.

**Comment by Wasala** [comment] 2015-02-10 11:20
Just to clarify my points further:

From the point of view of translators:

- They receive a html file, which is widely accepted by the tools 
- They can see strings in context, with the strings.xml segments are all over the file and provide no or minimal context for translation
- Since the format is html, they can preview translations (using their tools or browser)

- From the development team's perspective

- When we receive a huge word document with so  many updates to the FAQ content, and also a substantial amount of new content, it is easy to copy and paste content in this manner so minimal effort is required to update (but some minimal post processing will be required). Using the existing approach, you have to manually segment sentences, come up with meaningful keys and manually organise the strings file. Updating content is also difficult using the existing approach, as strings need to be located, changed etc.

- less queries to answer regarding contexts etc for localisers

- as the FAQ expands, it will be easy to maintain using this approach

In relation to your concern:
- this separation will result in only two formats: html (which is widely accepted by translation community and the strings.xml - custom/proprietary format) 
- As far as I know (can find the references if needed), most of the larger companies (including Microsoft, Oracle, Symantec  to name a few) uses two file formats for localisation; for example, EDB/XML/XLIFF/TMX for Software and HTML for static content like help files, website contents etc. So why should we deviate from the widely accepted industrial norm?

- I think the fall-back mechanism is easy to implement :) I will give it a try and if it is overly complex I will revert back to existing implementation

**Comment by spaceindaver** [comment] 2015-02-10 12:51
The strings file is not a proprietrary format, it is an Android standard that should be accepted by any tool that processes XML (which includes any HTML processing tools) so there is no advantage to switching to HTML from a standardisation point of view. The fallback mechanism is just an example of one of the many systems that would need to be reimplemented for the HTML files. It would mean the manual merging of files and translations instead of just using the already pre-existing tools that have been created around the strings.xml file. Dynamic loading, fallback support, version management, translation merging and many more systems wopuld have to be reimplemented for a single page of the system which fragments the localisation effort and breaks consistency.

You also don't seem to understand the massive benefit of seperating the content from the layout. It is an industry standard to seperate logic, content and layout so breaking this means you have to have a really good reason as it introduces interdependencies and plenty of other pitfalls that are avoided otherwise. Reorganising the strings.xml file would give you all the benefits you mentioned for switching to the HTML implementation without sacrificing the content/layout abstraction that is already in place.

The only real advantage I can see to the HTML implementation of the FAQ page is the ability for the translator to be able to see the translation in context. However, that will only work for the FAQ pages and all other strings in the site would not be viewable in context. When I left there was a plan to allow translators of the site to use the dev site to view all translations they provide in context by uploading their file and merging it into the dev sites localisation files. As far as I remember I wrote the tools for diffing the files and merging them again and @TheIceMageX50 wrote the page where the translator could upload their file and have it automatically merged and loaded. This is a far more robust solution than doing a single page in HTML and due to its general nature can apply to any string across the entire site. If you fragment the localisation into multiple formats it will break this approach making it entirely unmanagable from a dev perspective. A general solution is always better than writing bespoke solutions on a page by page basis and if you continue with this approach you will quickly find that site localisation takes more and more dev time when at the moment it is entirely tool based (i.e. run the diff tool to get the untranslated/changed strings, add that file to the site, get the output file and run the merge tool, add the updated strings file to the live site and you are done). If you split the localisation file you will have to do all the original localisation stuff (mentioned above) plus bespoke localisation work for every page you have removed from the strings file which will, in the best case scenario, double your workload when doing site localisation and, in the worst case, be a major headache when trying to figure out why layouts have suddenly changed due to an over zealous translation tool/translator or find that there is something you can no longer do because you have locked yourself into a less robust more static system.

**Comment by Paulina-Rosetta** [comment] 2015-02-10 13:31
I can't judge the technical aspect of this at all. My only concern is around dev time & effort. We have no problem finding localizers for the site, and sharing the strings with them, and answering basic questions, but we don't have the skills here to provide any support beyond that point. So whatever requires the least amount of intervention from devs gets my vote.

**Comment by TheIceMageX50** [comment] 2015-02-10 15:12
@Wasala I think Dave has made a lot of valid points here from what I glanced over already. The current system is certainly rather robust and "headache-preventing" in how it ensures translators (or their tools!) cannot accidentally break parts of the site, be it layout or otherwise.

@spaceindaver I could be forgetting something since I've been off the project for a while after going into 4th year but I don't think I wrote such a page (for translators to auto-merge)... @Wasala did you perhaps do something like that?

**Comment by Wasala** [comment] 2015-02-10 15:19
Thank you very much for your reply and your ideas. Meanwhile, I could successfully implement the fall-back mechanism :)

Strings file = Android standard = Proprietary
html = world wide standard

I do understand the advantages of separating content from the layout, but don't see much point here as FAQ is just a lot of static text and we have only one UI instance. hmm.. so whoever is still using html to represent static web based content (for l10n) should be really stupid :) 

Anyway, I still think the proposed approach is very much developer and localisers friendly as it will save a lot of time and hassles when it comes to updating FAQ content.So given the fact that only 1 instance of solas-match exists in the world, and only  1 developer is working, I am going to implement this approach as it is the easiest approach considering the current situation. While some of your comments make sense for extremely complex, fully automated ideal scenarios, we are far away from such a scenario. When the project reaches that stage, future developers can easily  revert back to Android strings.xml :)

**Comment by Wasala** [comment] 2015-02-10 15:28
@TheIceMageX50 I have a vague memory that @markcummins implemented this. But if he did, not sure why it no longer exists..

**Comment by TheIceMageX50** [comment] 2015-02-10 15:31
@Wasala Really? But Dave only wrote those tools shortly before he left when I was working there right? Or is it not so interconnected with the diff tools?

Also, in the initial post here you said "As it stands, it is very difficult to update the FAQ because of the distributed nature of FAQ's content within the strings files." Can I ask who thought that? Is it just how you feel for some reason, or did a translator complain?

**Comment by Wasala** [comment] 2015-02-10 15:38
@TheIceMageX50 I have got a 13 page Word document with the proposed changes/new content to the FAQ. I tried the existing approach for 2-3 days and I find it extremely tedious and stressful (because of inconsistent naming of keys, inconsistent ordering of strings, inconsistent segmentation, inconsistent place-holder inclusions etc). Then I thought about this idea. Which can be implemented in 1 day and will save time, not only for now but for future too. If you are around, I can show you the tasks involved (in old approach) and I am pretty sure you will get my point :)

**Comment by TheIceMageX50** [comment] 2015-02-10 15:43
(Was editing my last comment to post this but then saw your last comment)
Honestly I would think translators might have more issues with getting context for translating some of the text for dynamic content if anything because in some cases it might be a bit harder to point them to where it appears on site, or explain the context.
EDIT: But of course, I understand your approach has some merit if the reasons are related to the problems it has caused you.

One thing I do notice though after a quick glance through the FAQ.tpl file is that to be honest some of the templating is a bit of a mess and could do with cleaning up in that (unless I am misunderstanding) some parts seem to have 2 or 3 strings inserted one after another when those few strings could in fact be compressed into one. It would need some careful analysis to pick out whether in each case strings need to stay separate or not though I guess. If at some point we could indeed compress a lot of these strings, it would certainly reduce the internal fragmentation of FAQ strings within the strings.xml file.

**Comment by spaceindaver** [comment] 2015-02-10 21:50
I have to agree with @TheIceMageX50, if the problem is that the template file is difficult to work with and the strings file is poorly structured then the solution is to rework the template file and the strings file to be easier to work with. If you are having trouble with the tools that are there then you are better off fixing those tools instead of implementing a whole new solution with its own set of tools and workarounds. I understand that it might be easier to do the HTML solution for the FAQ page but the rest of the site will still be using the strings file and those tools so wouldn't it be better to improve the solution you have rather than implement a new one. If you do rework those tools and the strings file then the whole site will be better for it, not just a single, static page.

**Comment by Wasala** [comment] 2015-02-11 11:05
@TheIceMageX50  "some parts seem to have 2 or 3 strings inserted one after another when those few strings could in fact be compressed into one." 

Unfortunately I happened to learn a bit of "localisation" here :) So the problem with the above string "compression" is that we do this compression of sentences according to the syntax/semantics of English. In some other languages, English based segmentation might not work. For example, translators may run into problems conveying the intended meaning precisely in their own languages due to the way we have segmented content. If you have a closer look at various queries by the localisers of our site, you will realise we have this issue in lot of places. In other words, our code is not properly internationalised making localisation difficult. 

In relation to FAQ, if we leave them as HTML (at least for the moment), we have English html and other localised versions separately; and localisers will have full freedom to translate content to convey the exact meaning (for example,  they are not confined to translating 2 strings to get the exact same meaning and so on). 

In either case, as I have mentioned above, at this very moment, we are running on very low resources/and time issues so it is not worthwhile to spend 2-3 weeks working on FAQ/strings file. 

While I broadly agree with some of @spaceindaver 's comments, we will leave these ideas aside for the moment and revisit them when we are properly internationalising the code.

**Closed** 2015-03-23 14:15 UTC
Labels: feature-idea, Localisation, maintainability
